name: Rust CI Build

on:
  push:
    branches: main
  pull_request:
    branches: main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: 构建 CI 版本
    runs-on: windows-latest

    steps:
      - name: 签出代码
        uses: actions/checkout@v4

      - name: 安装 Rust 工具链
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: 'clippy, rustfmt'

      - name: 缓存 Cargo 依赖
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
      - name: 构建项目
        run: cargo build --verbose

      - name: 运行 Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: 运行 Rustfmt
        run: cargo fmt --all -- --check